# Generated by Django 5.1.5 on 2025-01-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("desc", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("quntity", models.IntegerField()),
            ],
        ),
    ]
