# Generated by Django 5.1.5 on 2025-01-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="image",
            field=models.CharField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT27gTKHqKhHk3i-EiarE5Q9IND_awvKaKjxw&s",
                max_length=5000,
            ),
        ),
    ]
