# Generated by Django 5.1.6 on 2025-02-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("summary", models.TextField(max_length=2000)),
                ("degree", models.CharField(max_length=200)),
                ("school", models.CharField(max_length=200)),
                ("university", models.CharField(max_length=200)),
                ("priviouswork", models.TextField(max_length=3000)),
                ("skills", models.TextField(max_length=4000)),
                ("certifications", models.TextField(max_length=4000)),
            ],
        ),
    ]
